name: Hermes Data Collection

on:
  schedule:
    # Run every day at 6:00 AM UTC (adjust timezone as needed)
    - cron: '0 6 * * *'
  
  # Allow manual triggering from GitHub UI
  workflow_dispatch:

jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas python-dotenv feedparser
    
    - name: Create .env file with secrets
      run: |
        echo "ALPHA_VANTAGE_KEY=${{ secrets.ALPHA_VANTAGE_KEY }}" >> .env
        echo "NASA_API_KEY=${{ secrets.NASA_API_KEY }}" >> .env
        echo "OPENWEATHER_KEY=${{ secrets.OPENWEATHER_KEY }}" >> .env
    
    - name: Run Markets Collector
      run: python services/markets/fetch_market_data.py
      continue-on-error: true
    
    - name: Run ISS Collector
      run: python services/space/fetch_iss_data.py
      continue-on-error: true
    
    - name: Run NEO Collector
      run: python services/space/fetch_neo_data.py
      continue-on-error: true
    
    - name: Run Solar Flare Collector
      run: python services/space/fetch_solar_data.py
      continue-on-error: true
    
    - name: Run Weather Collector
      run: python services/environment/fetch_weather_data.py
      continue-on-error: true
    
    - name: Run News Collector
      run: python services/social/fetch_news_data.py
      continue-on-error: true
    
    - name: Commit and push updated database
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add hermes.db
        git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Auto-update: Daily data collection $(date +'%Y-%m-%d')" && git push)
    
    - name: Create collection summary
      if: always()
      run: |
        echo "## 📊 Collection Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "✅ Data collection completed at $(date)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Database Status" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        python -c "import sqlite3; conn = sqlite3.connect('hermes.db'); cur = conn.cursor(); tables = ['stocks', 'iss_positions', 'near_earth_objects', 'solar_flares', 'weather', 'news']; [(print(f'{t}: {cur.execute(f\"SELECT COUNT(*) FROM {t}\").fetchone()[0]} records')) for t in tables]; conn.close()"
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
